### ISSUE TITLE
Create god-mode for testing

### ISSUE THREAD

**Issue by Paquito-San** [AlexRoijals/ProjectWormhole#53]
We need a god-mode for level testing. This mode will allow you to go through walls, fly and go ahead on the level.

**EXPECTED RESULT:**

_GodMode.cs file on Scripts folder_

**Comment by maideninblack** [comment]
- Free flyping + no clipping mode (camera)
- Reboot level 
- Trigger ending 
-

**Comment by Paquito-San** [comment]
This issue was completed on the following commit: da4c51da23cf9c80e795f514313f28bb9ea23a65
