### ISSUE TITLE
Create and implement  particle systems

### ISSUE THREAD

**Issue by Paquito-San** [AlexRoijals/ProjectWormhole#55]
Create the following particle systems and implement them:
- [ ] Small fire
- [ ] Big fire
- [ ] Small fog/mist
- [x] Big fog/mist
- [x] Wormhole particle system

**EXPECTED RESULT:**

_Particle system files on Particle System folder_

**Comment by maideninblack** [comment]
- Wormhole (when it opens up at the end of the iteration)
- Fog
- House in flames
- Dust of the character's steps
- Bright of the inventory when an item is picked up
